image: debian:stable

stages:
    - build

.build:
    stage: build

    script:
        - mkdir build
        - cd build
        - cmake -DCMAKE_C_COMPILER=$CMAKE_C_COMPILER -DCMAKE_CXX_COMPILER=$CMAKE_CXX_COMPILER
                ..
        - make

    artifacts:
        paths:
            - build/

build:gcc:
    extends: .build

    before_script:
        - apt-get update && apt-get install -y cmake g++

    variables:
        CMAKE_C_COMPILER: gcc
        CMAKE_CXX_COMPILER: g++

build:clang:
    extends: .build

    before_script:
        - apt-get update && apt-get install -y cmake clang

    variables:
        CMAKE_C_COMPILER: clang
        CMAKE_CXX_COMPILER: clang++
